version: "3.8"

services:
  web:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "skynet"
      POSTGRES_USER: "philanthropic"
      POSTGRES_PASSWORD: "narwhal"

  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://philanthropic:narwhal@db:5432/skynet"
      JWT_SECRET: "99AE99706241529D636298C3C0441FE927344BEB064972EC0AE2223CE8DE3C59"
